FROM python:3.10

RUN apt-get update && \
    apt-get install -y poppler-utils && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /app

WORKDIR /app

ADD requirements.txt /app/

RUN pip install -r requirements.txt

ADD . /app/

RUN rm -rf venv

EXPOSE 8081

VOLUME ["/app/logs"]

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8081", "--reload"]